name: Build and publish Docker container

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Containers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get -y install make
      - uses: docker/setup-buildx-action@v2

      - run: make docker-build-setup
      - run: make docker-build

      - run: echo "PLUGIN_VERSION=$(cat VERSION)-$(cat ITERATION)" >> $GITHUB_ENV

      - uses: softprops/action-gh-release@v1
        with:
          name: letsencrypt-cpanel-${{ env.PLUGIN_VERSION }}
          tag_name: ${{ env.PLUGIN_VERSION }}
          fail_on_unmatched_files: true

          files: |
            letsencrypt-cpanel-${{ env.PLUGIN_VERSION }}.x86_64.rpm
            letsencrypt-cpanel-${{ env.PLUGIN_VERSION }}.i386.rpm
            letsencrypt-cpanel_${{ env.PLUGIN_VERSION }}_amd64.deb
            letsencrypt-cpanel_${{ env.PLUGIN_VERSION }}_i386.deb

      - uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

permissions:
  contents: write
